In [ ]:
# importing numpy module

In [2]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.add(a,b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
np.subtract(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [10]:
a1 = np.add(a,b)

In [11]:
a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
#  It Returns the min of the values in the specified axis

In [12]:
a1.min()

2

In [13]:
a1.min(axis = 1)

array([ 2,  8, 14])

In [14]:
a1.min(axis = 0)

array([2, 4, 6])

In [15]:
a1.max()

18

In [16]:
a1.max(axis = 1)

array([ 6, 12, 18])

In [17]:
a1.max(axis = 0)

array([14, 16, 18])

In [18]:
np.sum(a1)

90

In [19]:
a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
a1[:,1]

array([ 4, 10, 16])

In [23]:
a1[1:,2]

array([12, 18])

In [24]:
np.argmax(a1)

8

In [28]:
np.argmax(a1,axis = 0)

array([2, 2, 2], dtype=int64)

In [29]:
np.argmax(a1,axis = 1)

array([2, 2, 2], dtype=int64)

In [30]:
np.argmin(a1)

0

In [31]:
np.argmin(a1, axis = 1)

array([0, 0, 0], dtype=int64)

In [32]:
np.argmin(a1, axis = 0)

array([0, 0, 0], dtype=int64)

In [33]:
np.sum(a1,axis = 1)

array([12, 30, 48])

In [34]:
np.sum(a1,axis = 0)

array([24, 30, 36])

In [35]:
np.mean(a1)

10.0

In [36]:
np.median(a1)

10.0

In [37]:
np.mode(a1)

AttributeError: module 'numpy' has no attribute 'mode'

In [38]:
np.std(a1)

5.163977794943222

In [39]:
np.var(a1)

26.666666666666668

In [40]:
np.sqrt(a1)

array([[1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162],
       [3.74165739, 4.        , 4.24264069]])

In [41]:
np.log(a1)

array([[0.69314718, 1.38629436, 1.79175947],
       [2.07944154, 2.30258509, 2.48490665],
       [2.63905733, 2.77258872, 2.89037176]])

In [42]:
a = np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [44]:
a[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [45]:
a[3:6]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [46]:
a[3:6,3]

array([34, 44, 54])

In [47]:
a[3:6,3:8]

array([[34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58]])

In [48]:
a[:,3:8]

array([[ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58],
       [64, 65, 66, 67, 68],
       [74, 75, 76, 77, 78],
       [84, 85, 86, 87, 88],
       [94, 95, 96, 97, 98]])

In [49]:
a[:,3:10:2]

array([[  4,   6,   8,  10],
       [ 14,  16,  18,  20],
       [ 24,  26,  28,  30],
       [ 34,  36,  38,  40],
       [ 44,  46,  48,  50],
       [ 54,  56,  58,  60],
       [ 64,  66,  68,  70],
       [ 74,  76,  78,  80],
       [ 84,  86,  88,  90],
       [ 94,  96,  98, 100]])

In [50]:
s = 'pytho'

In [51]:
s[2]

't'

In [52]:
s[:]

'pytho'